FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_API_URL=http://localhost:8070
ARG NEXT_PUBLIC_TOPICS_PAGE_SIZE=20
ARG NEXT_PUBLIC_INBOX_PAGE_SIZE=20
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_BFF_BASE_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_TOPICS_PAGE_SIZE=${NEXT_PUBLIC_TOPICS_PAGE_SIZE}
ENV NEXT_PUBLIC_INBOX_PAGE_SIZE=${NEXT_PUBLIC_INBOX_PAGE_SIZE}
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
COPY --from=builder /app /app
EXPOSE 3000
CMD ["npm", "run", "start", "--", "-p", "3000", "-H", "0.0.0.0"]
